In [1]:
%pip install -q pandas numpy
import pandas as pd
import numpy as np

[notice] A new release of pip available: 22.2.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

In [119]:
df = pd.read_csv("data/output/customers_education.csv")
df

,age,gender,education_level,region,marital_status,net_worth,cibil,kyc_status,date,id
0,32,F,Masters,Rural,Married,8700000,502,Compliant,2024-11-22,0
1,35,F,Bachelors,Urban,Married,9050000,535,Compliant,2024-11-26,1
2,34,M,Bachelors,Urban,Married,4200000,615,Compliant,2024-08-11,2
3,33,M,Bachelors,Urban,Married,3700000,536,Compliant,2024-09-16,3
4,35,F,Bachelors,Urban,Married,7500000,872,Compliant,2024-12-01,4
...,...,...,...,...,...,...,...,...,...,...
4999995,32,M,Masters,Urban,Married,9700000,892,Compliant,2024-09-29,4999995
4999996,32,M,Bachelors,Urban,Married,9300000,811,Compliant,2024-05-17,4999996
4999997,25,F,Masters,Urban,Unmarried,350000,378,Compliant,2024-05-18,4999997
4999998,43,M,Bachelors,Rural,Married,4600000,432,Compliant,2024-09-08,4999998
4999999,39,M,Bachelors,Rural,Married,5100000,808,Compliant,2024-12-05,4999999

In [104]:
#age-group:
df["age_group"] = np.random.choice(["18-21","21-30","30-35","35-40","40-45","45-50","50-55","55-60"],
                                   size=df.shape[0],
                                   p=[0.40,0.24,0.2,0.1,0.03,0.01,0.01,0.01])

In [47]:
df["age_group"].value_counts()

age_group
18-21    1999571
21-30    1201284
30-35    1000112
35-40     499139
40-45     149854
55-60      50132
50-55      50103
45-50      49805
Name: count, dtype: int64

In [48]:
##age
df["age"] = df["age_group"].apply(lambda x:np.random.randint(x.split('-')[0],x.split('-')[1])).astype('int')

In [39]:
##gender
df["gender"] = np.random.choice(["M","F"],size=df.shape[0],p=[0.55,0.45])

In [ ]:
#education level
df["education_level"] = "None"
df.loc[df["age"]<=24,"education_level"] = "Bachelors"
df.loc[df["age"]<=21,"education_level"] = "High School Diploma"
df.loc[(df["age"]>24),"education_level"] = np.random.choice(["Bachelors","Masters"], size=df.loc[(df["age"]>24)].shape[0],
                                                            p=[0.6,0.4])

In [ ]:
#region
df["region"] = np.random.choice(["Urban","Rural"],df.shape[0],p=[0.55,0.45])

In [68]:
#marital status
df["marital_status"] = np.random.choice(["Unmarried","Married"], size=df.shape[0],p=[0.2,0.8])
df.loc[(df["age"]<=24) & (df["gender"]=="M"),"marital_status"] = "Unmarried"
df.loc[(df["age"]<=21) & (df["gender"]=="F"),"marital_status"] = "Unmarried"

In [69]:
df["marital_status"].value_counts()

marital_status
Unmarried    2881959
Married      2118041
Name: count, dtype: int64

In [87]:
df["net_worth"] = 0
df.loc[(df["age"]<=20),"net_worth"] = np.random.randint(0,10,size=df.loc[(df["age"]<=20)].shape[0])*10000
df.loc[(df["age"]>20),"net_worth"] = np.random.randint(1,10,size=df.loc[(df["age"]>20)].shape[0])*50000
df.loc[(df["age"]>25),"net_worth"] = np.random.randint(3,201,size=df.loc[(df["age"]>25)].shape[0])*50000

In [85]:
df["cibil"] = 0
df.loc[(df["age"]<=20),"cibil"] = np.random.randint(300,750,size=df.loc[(df["age"]<=20)].shape[0])
df.loc[(df["age"]>20),"cibil"] = np.random.randint(350,900,size=df.loc[(df["age"]>20)].shape[0])
df.loc[(df["net_worth"]==0),"cibil"] = 0

In [88]:
df

,age_group,age,gender,education_level,region,marital_status,net_worth,cibil
0,30-35,32,F,Masters,Rural,Married,8700000,502
1,35-40,35,F,Bachelors,Urban,Married,9050000,535
2,30-35,34,M,Bachelors,Urban,Married,4200000,615
3,30-35,33,M,Bachelors,Urban,Married,3700000,536
4,35-40,35,F,Bachelors,Urban,Married,7500000,872
...,...,...,...,...,...,...,...,...
4999995,30-35,32,M,Masters,Urban,Married,9700000,892
4999996,30-35,32,M,Bachelors,Urban,Married,9300000,811
4999997,21-30,25,F,Masters,Urban,Unmarried,350000,378
4999998,40-45,43,M,Bachelors,Rural,Married,4600000,432
4999999,35-40,39,M,Bachelors,Rural,Married,5100000,808

In [105]:
df["kyc_status"] = np.random.choice(["Compliant","Non-Compliant"],size=df.shape[0],p=[0.9,0.1])

In [106]:
df = df.drop(columns="age_group",axis=1)
df

,age,gender,education_level,region,marital_status,net_worth,cibil,kyc_status
id,,,,,,,,
0,32,F,Masters,Rural,Married,8700000,502,Compliant
1,35,F,Bachelors,Urban,Married,9050000,535,Compliant
2,34,M,Bachelors,Urban,Married,4200000,615,Compliant
3,33,M,Bachelors,Urban,Married,3700000,536,Compliant
4,35,F,Bachelors,Urban,Married,7500000,872,Compliant
...,...,...,...,...,...,...,...,...
4999995,32,M,Masters,Urban,Married,9700000,892,Compliant
4999996,32,M,Bachelors,Urban,Married,9300000,811,Compliant
4999997,25,F,Masters,Urban,Unmarried,350000,378,Compliant
4999998,43,M,Bachelors,Rural,Married,4600000,432,Compliant
4999999,39,M,Bachelors,Rural,Married,5100000,808,Compliant

In [101]:
df

,age,gender,education_level,region,marital_status,net_worth,cibil,id,date,kyc_status
0,32,F,Masters,Rural,Married,8700000,502,0,2024-11-22,Compliant
1,35,F,Bachelors,Urban,Married,9050000,535,1,2024-11-26,Compliant
2,34,M,Bachelors,Urban,Married,4200000,615,2,2024-08-11,Compliant
3,33,M,Bachelors,Urban,Married,3700000,536,3,2024-09-16,Compliant
4,35,F,Bachelors,Urban,Married,7500000,872,4,2024-12-01,Compliant
...,...,...,...,...,...,...,...,...,...,...
4999995,32,M,Masters,Urban,Married,9700000,892,4999995,2024-09-29,Compliant
4999996,32,M,Bachelors,Urban,Married,9300000,811,4999996,2024-05-17,Compliant
4999997,25,F,Masters,Urban,Unmarried,350000,378,4999997,2024-05-18,Compliant
4999998,43,M,Bachelors,Rural,Married,4600000,432,4999998,2024-09-08,Compliant
4999999,39,M,Bachelors,Rural,Married,5100000,808,4999999,2024-12-05,Compliant

In [108]:
df1 = pd.read_csv("data/output/customers.csv")
df["date"] = df1["date"]

In [112]:
df["id"] = df.index

In [118]:
df.to_csv("data/output/customers_education.csv",index=False)

NameError: name 'df' is not defined